plugins { id 'com.android.application' }

android {
    buildFeatures {
        buildConfig true
    }

    namespace 'app.rafiq.muslim'
    compileSdk 34

    defaultConfig {
        applicationId "app.rafiq.muslim"
        minSdk 26
        targetSdk 34
        versionCode 5
        versionName "1.4"
    }

    signingConfigs {
        release {
            def keystoreFile = System.getenv("KEYSTORE_FILE")
            if (keystoreFile) {
                storeFile file(keystoreFile)
                storePassword System.getenv("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEYSTORE_ALIAS")
                keyPassword System.getenv("KEYSTORE_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'androidx.core:core:1.12.0'
}
